language: cpp

services:
  - docker

sudo: required
dist: trusty
osx_image: xcode8.3

env:
  global:
    - QT_VER=5.9.1
    - ZLIB_VERSION=1.2.11
    - ZLIB_CHECKSUM=4ff941449631ace0d4d203e3483be9dbc9da454084111f97ea0a2114e19bf066
    - LIBPNG_VERSION=1.6.34
    - LIBPNG_CHECKSUM=c05b6ca7190a5e387b78657dbe5536b2

matrix:
  include:
    - os: linux
      env:
        - PLATFORM=gcc_64
        - BUILD_DOC=true
    - os: osx
      env:
        - PLATFORM=clang_64

before_install:
  - git clone https://github.com/Skycoder42/QtModules.git ./qtmodules-travis
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then travis_wait 40 ./qtmodules-travis/ci/$TRAVIS_OS_NAME/setup.sh; else ./qtmodules-travis/ci/$TRAVIS_OS_NAME/setup.sh; fi

script:
  - ./qtmodules-travis/ci/$TRAVIS_OS_NAME/build.sh

before_deploy:
  - ./qtmodules-travis/ci/$TRAVIS_OS_NAME/upload-prepare.sh
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: <secret key>
  file_glob: true
  file: install/opt/build_*_$QT_VER.tar.xz
  on:
    repo: Skycoder42/qapng
    tags: true

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
