image:
  - Visual Studio 2017
  - Visual Studio 2015

version: build-{build}

environment:
  QT_VER: 5.9.1
#  EXTRA_MODULES: 

  matrix:
    - PLATFORM: msvc2017_64
    - PLATFORM: msvc2015_64
    - PLATFORM: msvc2015
    - PLATFORM: mingw53_32

matrix:
  exclude:
    - PLATFORM: msvc2017_64
      image: Visual Studio 2015
    - PLATFORM: mingw53_32
      image: Visual Studio 2015
    - PLATFORM: msvc2015_64
      image: Visual Studio 2017
    - PLATFORM: msvc2015
      image: Visual Studio 2017

install:
  - git clone https://github.com/Skycoder42/QtModules.git .qtmodules-travis
  - .qtmodules-travisciwinsetup.bat

build_script:
  - .qtmodules-travisciwinbuild.bat

after_build:
  - .qtmodules-travisciwinupload-prepare.bat

artifacts:
  - path: installbuild_*_%QT_VER%.zip

deploy:
  provider: GitHub
  auth_token:
    secure: <secret key>
  artifact: /.*.zip/
  force_update: false
  on:
    appveyor_repo_tag: true
